spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user-service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

validity_period_of_card: 5

#logging:
#  level:
#    root: INFO
#    liquibase: DEBUG

